---
- name: Archive log configuration
  hosts: r7
  tasks: 
    - name: Configure archive log
      cisco.ios.ios_config:
        lines:
          - record rc
          - logging enable
        parents:
          - archive
          - log config

      register: archive_config

    - name: Print the output
      ansible.builtin.debug:
        msg: "{{ archive_config }}"
 
    